In [1]:
from evaluation import evaluate
from data_reader import read_df, interaction_matrix

df = read_df('train')
_, _, R = interaction_matrix(df)

evaluate(R, df)
# res = evaluate(R, df)

ValueError: select kind must be 'introselect' (got 'mergesort')

In [16]:
import numpy

n = 4
arr = -numpy.array([3,3,1,4,2,4,2])

# Unordered:
indices = numpy.argpartition(arr, -n)[-1:-n-1]

# Extra code if you need the indices in order:
min_elements = arr[indices]
min_elements_order = numpy.argsort(min_elements)
ordered_indices = indices[min_elements_order]
ordered_indices

array([1, 0, 3, 5])

In [17]:
from evaluation import topk

topk(arr.reshape((1, 7)), 4)

array([[3, 5, 1, 0]])

In [13]:
min_elements

array([-4, -4, -3, -3])

In [3]:
indices

array([4, 6, 2, 0])

In [5]:
ordered_indices

array([2, 4, 6, 0])

In [6]:
len(gold[0])

NameError: name 'gold' is not defined

In [9]:
len(set(guess[0]).intersection(gold[0]))

20

In [7]:
print(gold[0])

[68, 84, 548, 69, 134, 252, 96, 119, 597, 371, 23, 123, 50, 601, 83, 355, 279, 82, 22, 575, 400, 563, 289, 253, 209, 322, 81, 361, 198, 389, 115, 633, 75, 375, 561, 25, 224]


In [7]:
res['rank correlation']

array([-0.36273115,  1.        , -0.38701299, ..., -0.15583075,
       -0.28740824,  1.        ])

In [6]:
print(gold[2])
guess[2, :20]

[590, 355, 300, 387, 271, 563, 96, 403, 562, 34, 426, 577, 591, 282, 388, 246, 31, 237, 274, 371, 360]


array([426,  31, 360,  96, 274, 590, 355, 371,  34, 237, 282, 246, 562,
       563, 403, 300, 387, 388, 577, 591])

In [13]:
from evaluation import topk, rank_correlation

g = topk(R, 15)
rank_correlation(g, R)

array([ 1.        , -0.33928571,  1.        , ...,  1.        ,
        1.        ,  0.03571429])

In [1]:
from evaluation import topk, rank_correlation

g = topk(R, 15)
rank_correlation(g, R)

NameError: name 'R' is not defined

In [14]:
len(gold[1])

10

In [11]:
np.take_along_axis(R, g, axis=1)

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 0., 0.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 0., 0., 0.]])

In [9]:
20/37

0.5405405405405406

In [6]:
res['recall'].argmin()

931

In [8]:
R[931].sum()

89.0