In [1]:
import numpy as np

In [2]:
a = np.random.random((4,))
a

array([[0.51323802, 0.98955509],
       [0.48097214, 0.15087868],
       [0.25549841, 0.87235546],
       [0.20715752, 0.76346878]])

In [3]:
e = np.exp(a)
e

array([[1.67069219, 2.69003737],
       [1.61764622, 1.16285557],
       [1.29110496, 2.39253976],
       [1.23017634, 2.14570631]])

In [4]:
s = e.sum(axis=1)
s

array([4.36072956, 2.78050179, 3.68364473, 3.37588265])

In [5]:
r = np.vstack((s,s)).T
r

array([[4.36072956, 4.36072956],
       [2.78050179, 2.78050179],
       [3.68364473, 3.68364473],
       [3.37588265, 3.37588265]])

In [6]:
e / r

array([[0.38312217, 0.61687783],
       [0.58178212, 0.41821788],
       [0.3504966 , 0.6495034 ],
       [0.36440139, 0.63559861]])